config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :notes
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static#home'
  get 'tagged' => 'notes#tagged', :as => 'tagged'
  get 'join' => 'notes#join', :as => 'join'
  post 'export_email' => 'notes#export_email', :as => 'export_email'

  # To mount Action Cable, and to listen to ws://localhost:3000/cable
  mount ActionCable.server => '/cable'

end

app/models/note.rb
class Note < ApplicationRecord

  belongs_to :creator, class_name: "User", optional:true
  has_and_belongs_to_many :users

  validates :text, presence: true

  acts_as_taggable_on :tags

  before_create :generate_random_id

  private

  def generate_random_id
    begin
      self.id = SecureRandom.random_number(10000000)
    end while Note.where(id: self.id).exists?
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all.order('created_at DESC')
    @note = Note.new
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)
    current_user.notes << @note

    # SUMMARIZER: Send post request to summarization API with given parameters
    response = Unirest.post "https://textanalysis-text-summarization.p.mashape.com/text-summarizer-text",
    headers:{
      "X-Mashape-Key" => "aosLn4ArKSmshDQj2fLRpXFdIjKep1G9sPcjsnzUapJMEo5TUT",
      "Content-Type" => "application/x-www-form-urlencoded",
      "Accept" => "application/json"
    },
    parameters:{
      "sentnum" => 3,
      "text" => @note.text
    }

    # AUTO TAGGER: Send post request to Google NL API with given parameters
    tag_scraper = Unirest.post "https://language.googleapis.com/v1/documents:analyzeEntities?key=AIzaSyA4A03W32VwKt313lZiEVD4_47P2A9lMeQ",
    headers:{
      "Content-Type" => "application/json"
    },
    parameters: JSON.generate({
        "encodingType": "UTF8",
        "document": {
          "type": "PLAIN_TEXT",
          "content": @note.text}})

    # Set up array and push relevant entities into the array, then remove repeated entities and sort it alphabetically
    tag_arr = []
    tag_scraper.body["entities"].each do |entity|
      if entity["type"] != "OTHER"
        tag_arr.push(entity["name"])
      end
    end
    tag_arr.uniq!
    tag_arr.sort_by!(&:downcase)

    @note.tag_list = tag_arr
    @note.summary = response.body["sentences"].join(" ")
    @note.creator_id = current_user.id
    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update

    # Resend updated text through APIs
    # SUMMARIZER: Send post request to summarization API with given parameters
    response = Unirest.post "https://textanalysis-text-summarization.p.mashape.com/text-summarizer-text",
    headers:{
      "X-Mashape-Key" => "aosLn4ArKSmshDQj2fLRpXFdIjKep1G9sPcjsnzUapJMEo5TUT",
      "Content-Type" => "application/x-www-form-urlencoded",
      "Accept" => "application/json"
    },
    parameters:{
      "sentnum" => 3,
      "text" => @note.text
    }

    # AUTO TAGGER: Send post request to Google NL API with given parameters
    tag_scraper = Unirest.post "https://language.googleapis.com/v1/documents:analyzeEntities?key=AIzaSyA4A03W32VwKt313lZiEVD4_47P2A9lMeQ",
    headers:{
      "Content-Type" => "application/json"
    },
    parameters: JSON.generate({
        "encodingType": "UTF8",
        "document": {
          "type": "PLAIN_TEXT",
          "content": @note.text}})

    # Set up array and push relevant entities into the array, then remove repeated entities and sort it alphabetically
    tag_arr = []
    tag_scraper.body["entities"].each do |entity|
      if entity["type"] != "OTHER"
        tag_arr.push(entity["name"])
      end
    end
    tag_arr.uniq!
    tag_arr.sort_by!(&:downcase)

    @note.tag_list = tag_arr
    @note.summary = response.body["sentences"].join(" ")

    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def tagged
    if params[:tag].present?
      @notes = Note.tagged_with(params[:tag])
    else
      @notes = Note.postall
    end
  end

  def join
    @note = Note.find(params[:id])
    current_user.notes << @note
    flash[:notice] = "You have been granted access to this note."
    redirect_to note_path(@note)
  end

  def export_email
    ExportNoteMailer.export_note(current_user, Note.find(params[:id])).deliver
    flash[:notice] = "Note has been exported and sent to your email address."
    redirect_to notes_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:title, :location, :text, :summary, :tag_list)
    end
end

app/helpers/notes_helper.rb
module NotesHelper

end

app/views/notes/_form.html.erb
<div class="container content">

    <%= form_for(note) do |f| %>
    <% if note.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(note.errors.count, "error") %>
            prohibited this note from being saved:</h2>

        <ul>
            <% note.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
        </ul>
    </div>
    <% end %>

    <% if note.users.first.id == current_user.id %>
      <div class="field">
          <%= f.label :title, class:"label" %>
          <%= f.text_field :title, class:"input", id:"note-title" %>
      </div>

      <div class="field">
          <%= f.label :location, class:"label" %>
          <%= f.text_field :location, class:"input", id:"note-location" %>
      </div>
    <% else %>
      <div class="field">
          <%= f.label :title, class:"label" %>
          <%= f.text_field :title, class:"input", id:"note-title", disabled:true %>
      </div>

      <div class="field">
          <%= f.label :location, class:"label" %>
          <%= f.text_field :location, class:"input", id:"note-location", disabled:true %>
      </div>
    <% end %>

    <div class="field">
        <label class="label">Text
          <div class="is-pulled-right">
            <span id="text-label" class="tag is-dark" style="font-size:0.7em">Detecting connection... </span>
            <span class="tag is-warning" id="active-editors">Active Editors: <%= ActionCable.server.connections.length %></span>
          </div>
        </label>

        <%= f.text_area :text, class:"textarea", id:"note-text" %>
    </div>

    <div class="actions">
        <%= f.submit 'Submit', class:"button is-primary"%>
        <%= link_to 'Back to Note', @note, class:"button is-warning" %>
        <%= link_to 'View All Notes', notes_path, class:"button is-warning" %>
    </div>
    <% end %>

</div>

app/views/notes/_newform.html.erb
    <%= form_for(note) do |f| %>
    <% if note.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(note.errors.count, "error") %>
            prohibited this note from being saved:</h2>

        <ul>
            <% note.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
        </ul>
    </div>
    <% end %>

    <div class="field">
        <%= f.label :title, class:"label" %>
        <%= f.text_field :title, class:"input", id:"note-title" %>
    </div>

    <div class="field">
        <%= f.label :location, class:"label" %>
        <%= f.text_field :location, class:"input", id:"note-location" %>
    </div>

    <div class="field">
        <label class="label">Text</label>
        <%= f.text_area :text, class:"textarea", id:"note-text"%>
    </div>

    <div class="actions">
        <%= f.submit 'Create New Note', class:"button is-primary"%>
        <%= link_to 'Back to Notes', notes_path, class:"button is-warning" %>
    </div>
    <% end %>

app/views/notes/edit.html.erb
<br>
<div class="container content">

    <h1>Edit: <i><%=@note.title%></i>

    <% if @note.users.first.id == current_user.id %>
      <span class="button is-warning is-pulled-right is-large">
        <span class="icon">
        <i class="fa fa-user-circle-o"></i>
        </span>
        <b>Creator</b>
      </span>
    <% else %>
      <span class="button is-info">
        <span class="icon">
        <i class="fa fa-id-badge"></i>
        </span>
        <b>Contributor</b>
      </span>
    <% end %>

    </h1>

    <%= render 'form', note: @note %>

</div>

<script>
  var current_note_id = <%= @note.id.to_i %>
  var current_user_id = <%= current_user.id %>
</script>

app/views/notes/index.html.erb
<br>
<div class="container content">

    <% greetings = ["Hello", "Heya", "Howdy", "How's it going", "What's up", "Looking good", "Hope it's been a good day", "Ahoy", "Greetings", "Aloha", "Hey", "Hi", "Ello", "Sup", "Welcome back"] %>
    <h1><%= greetings.sample %>,
        <%= current_user.name.split(" ").first %>.</h1>

    <div class="field has-addons">
        <p class="control">
            <button id="toggle-new-note" , class="button is-primary">Create new note</button>
        </p>
        <p class="control is-expanded">
            <span class="select is-fullwidth">
                <select name="note" id="dropdown">
                    <option value="" data-link="<%= notes_path %>">Or find one of your previous notes</option>
                    <% @notes.each do |note| %>
                    <% if current_user.notes.include?(note) %>
                    <option value="<%= note.id %>" data-link="<%= note_path(note.id) %>"><%= note.title %>
                        (<%= note.created_at.localtime.strftime("%e/%m/%y, %I:%M %p") %>)</option>
                    <% end %>
                    <% end %>
                </select>
            </span>
        </p>
        <p class="control">
            <a href="<%= notes_path %>" id="dropdown-link" class="button is-primary">
                <span class="icon">
                    <i class="fa fa-chevron-right"></i>
                </span>
            </a>
        </p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Title</th>
                <th>Created</th>
                <th>Summary</th>
                <th>Creator</th>
                <th>Contributors</th>
                <th>Tags</th>
                <th colspan="2"></th>
            </tr>
        </thead>

        <tbody>
            <% @notes.each do |note| %>
            <% if current_user.notes.include?(note) %>
            <tr>
                <td>
                    <%= link_to note.title, note, class:"button is-outlined is-small is-primary" %>
                </td>
                <td><%= note.created_at.localtime.strftime("%e/%m/%y, %I:%M %p") %></td>
                <td><%= note.summary.split(" ")[0..10].join(" ") %>...</td>
                <td><%= note.creator.name %></td>
                <td>
                    <% note.users.each do |user| %>
                    <% if user.name != note.creator.name %>
                    <%= user.name %><br>
                    <% end %>
                    <% end %>
                </td>
                <% note.tags.any? %>
                <td><% note.tags.each do |tag| %>
                    <%= link_to tag.name, tagged_url(:tag => tag.name), class:"tag is-primary", style:"margin:2px; font-size:0.8em" %>
                    <% end %>
                </td>
                <td><%= link_to '<i class="fa fa-pencil"></i>'.html_safe, note, class:"button is-primary"%></td>
                <% if note.creator.id == current_user.id %>
                <td><%= link_to '<i class="fa fa-trash"></i>'.html_safe, note, method: :delete, data: { confirm: 'Are you sure?' }, class:"button is-primary" %></td>
                <% end %>
            </tr>

            <% end %>
            <% end %>
        </tbody>
    </table>

    <button id="toggle-new-note" , class="button is-primary">Create new note</button>

</div>

<div class="modal" id="modal-new-note">
    <div class="modal-background"></div>
    <div class="modal-content">
        <div class="notification">
            <button class="delete is-pulled-right" id="toggle-new-note"></button>
            <h1 class="title">Create new note</h1>
            <%= render 'newform', note: @note %>
        </div>
    </div>
    <button class="modal-close" id="toggle-new-note"></button>
</div>

<script>

    $('select').change(function () {
        console.log('params changed')
        $('select option:selected').each(function () {
            var link = $(this).data('link')
            $('#dropdown-link').attr('href', link)
        })
    })

    $('[id=toggle-new-note]').click(function () {
        $('#modal-new-note').toggleClass('is-active')
    })
</script>

app/views/notes/new.html.erb
<br>
<div class="container content">

<h1>New Note</h1>

<%= render 'newform', note: @note %>

</div>

app/views/notes/show.html.erb
<br><br>

<div class="container">

<div class="card shadow">

<header class="card-header" style="padding: 20px">
  <h1 class="title left"><%= @note.title %></h1>
</header>

<div class="card-content">

  <div class="field has-addons" style="padding:0">
    <p class="control is-expanded">
      <input class="input is-medium" id="url" value="<%= request.original_url %>">
    </p>
    <p class="control">
      <button class="clipboard-btn button is-primary is-medium" data-clipboard-action="copy" data-clipboard-target="#url" title="Copy URL to share with another user">
      <i class="fa fa-clipboard"></i>
      </button>
    </p>
  </div>

<p>
  <h3><strong>Summary:</strong><br>
  <%= @note.summary %><br><br></h3>
</p>

<p>
  <h3><strong>Original Notes:</strong><br>
  <%= @note.text %><br><br></h3>
</p>

<p>
<% @note.tags.any? %>
  <% @note.tags.each do |tag| %>
  <%= link_to tag.name, tagged_url(:tag => tag.name), class:"tag is-primary", style:"margin:2px; font-size:0.8em" %>
<% end %><br><br>
</p>

<p><i>
  <%= @note.location %>,
  <%= @note.created_at.localtime.strftime("%e %B %Y, %I:%M %p") %><br>
</i></p>

</div>

<footer class="card-footer">

  <%= link_to 'Back', notes_path, class:"card-footer-item" %>
  <% if @note.creator_id == current_user.id || current_user.notes.include?(@note) %>
  <%= link_to 'Edit'.html_safe, edit_note_path(@note), class:"card-footer-item" %>
  <%= link_to 'PDF', note_path(@note, format:"pdf"), class:"card-footer-item" %>
  <%= link_to 'Email', export_email_path(id: @note.id), class:"card-footer-item", method: :post %>
  <% else %>
  <%= link_to 'Join', join_path(id: @note.id), class:"card-footer-item" %>
  <% end %>

</footer>

</div>
</div>

<br><br>

<script>
  $(document).ready(function() {
    var clipboard = new Clipboard('.clipboard-btn')
    console.log(clipboard)
  })
</script>

app/views/notes/tagged.html.erb
<div class="container content">

<h1>Notes tagged with '<%= params.first[1] %>' </h1>

<%= link_to 'New Note', new_note_path, class:"button is-primary" %>
<%= link_to 'View All Notes', notes_path, class:"button is-warning" %>

<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Created</th>
            <th>Summary</th>
            <th>Creator</th>
            <th>Contributors</th>
            <th>Tags</th>
            <th colspan="2"></th>
        </tr>
    </thead>

    <tbody>
        <% @notes.each do |note| %>
        <% if current_user.notes.include?(note) %>
        <tr>
            <td><%= link_to note.title, note, class:"button is-outlined is-small is-primary" %></td>
            <td><%= note.created_at.localtime.strftime("%e/%m/%y, %I:%M %p") %></td>
            <td><%= note.summary %></td>
            <td><%= note.creator.name %></td>
            <td>
              <% note.users.each do |user| %>
              <% if user.name != note.creator.name %>
              <%= user.name %><br>
              <% end %>
              <% end %>
            </td>
            <td><% note.tags.each do |tag| %>
              <%= link_to tag.name, tagged_url(:tag => tag.name), class:"tag is-primary", style:"margin:2px; font-size:0.8em" %>
            <% end %>
            </td>
            <td><%= link_to '<i class="fa fa-pencil"></i>'.html_safe, note, class:"button is-primary"%></td>
            <% if note.creator.id == current_user.id %>
            <td><%= link_to '<i class="fa fa-trash"></i>'.html_safe, note, method: :delete, data: { confirm: 'Are you sure?' }, class:"button is-primary" %></td>
            <% end %>
        </tr>
        <% end %>
        <% end %>
    </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path, class:"button is-primary" %>
<%= link_to 'View All Notes', notes_path, class:"button is-warning" %>

</div>