config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :notes
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static#home'
  get 'tagged' => 'notes#tagged', :as => 'tagged'
  get 'join' => 'notes#join', :as => 'join'
  post 'export_email' => 'notes#export_email', :as => 'export_email'

  # To mount Action Cable, and to listen to ws://localhost:3000/cable
  mount ActionCable.server => '/cable'

end

app/views/partials/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="content has-text-centered">
      <h6>
        <img src="http://i.imgur.com/CiHuxJE.png?1" width="200">
        <br><br>
        Take notes. Never worry about them again.
        <br><br>
        <small><i>Icons from <a href="http://www.flaticon.com" title="Flaticon">Flaticon.com</a>, licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></i></small>
      </h6>
      <p>
        <a class="icon" href="https://github.com/jonathanlimes/telder">
          <i class="fa fa-github is-primary"></i>
        </a>
        <a class="icon" href="mailto:jonathanlimes@gmail.com">
          <i class="fa fa-envelope-o"></i>
        </a>
      </p>
    </div>
  </div>
</footer>

app/views/partials/_navbar.html.erb
<nav class="nav has-shadow">
    <div class="container">
        <div class="nav-left nav-menu">
            <a href="/" class="nav-item">
                <img src="http://i.imgur.com/KnWaDeC.png?1" width="70">
            </a>
            <% if user_signed_in? %>
            <%= link_to "My Notes", notes_path, class: "nav-item is-tab" %>
            <%= link_to "New Note", new_note_path, class:"nav-item is-tab" %>
            <% end %>
        </div>
        <div class="nav-right nav-menu is-hidden-mobile">
            <% if user_signed_in? %>
                <%= link_to current_user.name, user_path(current_user), class:"nav-item is-tab is-hidden-mobile" %>
                <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"nav-item is-tab is-hidden-mobile" %>
            <% else %>
                <a id="toggle-modal-login" class="nav-item is-tab">Login</a>
                <a id="toggle-modal-signup" class="nav-item is-tab">Sign Up</a>
            <% end %>
            </div>
        </div>
    </nav>