config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :notes
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static#home'
  get 'tagged' => 'notes#tagged', :as => 'tagged'
  get 'join' => 'notes#join', :as => 'join'
  post 'export_email' => 'notes#export_email', :as => 'export_email'

  # To mount Action Cable, and to listen to ws://localhost:3000/cable
  mount ActionCable.server => '/cable'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :notes

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end

  def after_sign_up_path_for(resource)
    notes_path
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<div class="container profile">
    <div class="section profile-heading">
        <div class="card columns">
            <div class="column is-2">
                <div class="image is-128x128 avatar">
                    <img src="https://api.adorable.io/avatars/285/<%= @user.email %>.png">
                </div>
            </div>
            <div class="column is-3 name">
                <h1>
                    <span class="title is-bold"><%= @user.name %></span>
                </h1>
                <h5 class="tagline">
                    <i><%= @user.email %></i>
                </h5>
                <h5 class="tagline">
                    <small>Member since
                        <%= @user.created_at.strftime("%e %B %Y") %></small>
                </h5>

                <% if current_user.id == @user.id %>
                  <button class="button is-primary" id="toggle-modal-edit-user">Edit Profile</button>
                <% end %>

            </div>
            <div class="column is-1 has-text-centered">
                <br>
                <% if @user.notes.last %>
                <h3 class="title"><%= @user.notes.length %></h3>
                <h3 class="subtitle">Notes</h3>
                <% end %>
            </div>
            <div class="column is-3 has-text-centered">
                <br>
                <% if @user.notes.last %>
                <h3 class="title"><%= @user.notes.last.updated_at.localtime.strftime("%e/%m/%y, %I:%M %p") %></h3>
                <h3 class="subtitle">Last Activity</h3>
                <% end %>
            </div>
            <div class="column is-3 has-text-centered">
                <br>
                <% if @user.notes.last %>
                <h3 class="title"><%= @user.last_sign_in_at.localtime.strftime("%e/%m/%y, %I:%M %p") %></h3>
                <h3 class="subtitle">Last Login</h3>
                <% end %>
            </div>
        </div>
    </div>
</div>

<div class="modal" id="modal-edit-user">
    <div class="modal-background"></div>
    <div class="modal-content">
        <div class="notification">
            <button class="delete is-pulled-right" id="toggle-modal-edit-user"></button>
            <h1 class="title">Edit User Profile</h1>

            <%= form_for(:user, url: registration_path(:user), html: { method: :put }) do |f| %>
            <%= devise_error_messages! %>

            <div class="field">
                <%= f.label :name, class:"label" %>
                <%= f.text_field :name, autofocus: true, class:"input"%>
            </div>

            <div class="field">
                <%= f.label :email, class:"label" %>
                <%= f.email_field :email, autofocus: true, class:"input" %>
            </div>

            <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
            <div>Currently waiting confirmation for:
                <%= resource.unconfirmed_email %></div>
            <% end %>

            <div class="field">
                <%= f.label :password, class:"label" %>
                <i>(leave blank if you don't want to change it)</i>
                <%= f.password_field :password, autocomplete: "off", class:"input" %>
                <% if @minimum_password_length %>
                <br/>
                <em><%= @minimum_password_length %>
                    characters minimum</em>
                <% end %>
            </div>

            <div class="field">
                <%= f.label :password_confirmation, class:"label" %>
                <%= f.password_field :password_confirmation, autocomplete: "off", class:"input" %>
            </div>

            <div class="field">
                <%= f.label :current_password, class:"label" %>
                <i>(we need your current password to confirm your changes)</i>
                <%= f.password_field :current_password, autocomplete: "off", class:"input" %>
            </div>

            <div class="actions">
                <%= f.submit "Update", class:"button is-primary" %>
            </div>
            <% end %>

            <h3>Cancel my account</h3>
            <small>
                We'd hate to see you go.</small><br><br>
            <%= button_to "Delete account", registration_path(:user), data: { confirm: "Are you sure?" }, method: :delete, class:"button is-dark" %>

        </div>
    </div>
    <button class="modal-close" id="toggle-modal-edit-user"></button>
</div>

<script>

    $('[id=toggle-modal-edit-user]').click(function () {
        $('#modal-edit-user').toggleClass('is-active')
    })
</script>